namespace: beta # 手动指定为dev环境下方也需要修改

resources:
  - ../../base

configMapGenerator:
  - name: auth-service-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=beta # 手动指定为dev环境，上方也需要修改
    files:
      - application-beta.yml

secretGenerator:
  - name: auth-connect-secret
    envs:
      - connect.env.secret
    options:
      labels:
        secret.group: auth-connect # spring-cloud 通过这个自定义label寻找secret
  - name: redis-access-secret
    envs:
      - redis.env.secret
    options:
      labels:
        secret.group: cache-access-secret

patches:
  - path: deployment-patch.yaml