apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SPRING_PROFILES_ACTIVE: "default"
  application.yml: |
    spring:
      application:
        name: auth-service
    server:
      port: 8080
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
          write-dates-as-timestamps: false
        time-zone: UTC
      messages:
        basename: i18n/message
        encoding: utf-8
        sentinel:
          eager: false
          transport:
            dashboard: ${SENTINEL_HOST:127.0.0.1}:8858

    feign:
      sentinel:
        enabled: true # @FeignClient将会被自动添加@SentinelResource

    # 雪花ID配置
    snowflake:
      datacenter-id: ${DATACENTER_ID:1} # 不能超过31
      machine-id: ${MACHINE_ID:1} # 不能超过31

    # 默认关闭spring doc
    springdoc:
      swagger-ui:
        enabled: false
      api-docs:
        enabled: false
    
    # 防止过分暴露
    management:
      server:
        port: 8081
      endpoints:
        web:
          exposure:
            include: health, info